const string Ninja_MaxXPHelper_SectionName = "MaxXPHelper-V1";
// todo: expose some as ini options
const int Ninja_MaxXPHelper_IconSize = 50;
const int Ninja_MaxXPHelper_MinIconSize = 10;
const int Ninja_MaxXPHelper_IconFadingNearbyDistance = 2000;
const int Ninja_MaxXPHelper_SystemAlertDuration = 2000;
const int Ninja_MaxXPHelper_ColorMaxFloat = 255;
const int Ninja_MaxXPHelper_ColorMaxInt = 255;

// For reference: 
// https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3drenderstatetype
const int Ninja_MaxXPHelper_D3DRENDERSTATE_D3DRS_ALPHAREF = 24;
const int Ninja_MaxXPHelper_D3DRENDERSTATE_D3DRS_ALPHATESTENABLE = 15;