const string Ninja_MaxXPHelper_SectionName = "MaxXPHelper-V1";
// todo: expose some as ini options
const int Ninja_MaxXPHelper_IconSize = 200;
const int Ninja_MaxXPHelper_MinIconSize = 10;
const int Ninja_MaxXPHelper_IconFadingNearbyDistance = 2000;
const int Ninja_MaxXPHelper_SystemAlertDuration = 2000;
const int Ninja_MaxXPHelper_ColorMaxFloat = 255;
const int Ninja_MaxXPHelper_ColorMaxInt = 255;