const string Ninja_MaxXPHelper_SectionName = "MaxXPHelper-V1";
// todo: expose as ini options?
const int Ninja_MaxXPHelper_SphereColorNotBeaten = 2663464;
const int Ninja_MaxXPHelper_SphereColorConsiderG1DoubleXPGlitch = 16729882;
const int Ninja_MaxXPHelper_SphereColorNotLoadedIntoGameYet = 2663464;
const int Ninja_MaxXPHelper_SphereColorDeathAlert = 15120384;
const int Ninja_MaxXPHelper_SphereRadius = 100;