const string Ninja_MaxXPHelper_TrackersUseZBuffer_OptKey = "trackersUseZBuffer";

const int Ninja_MaxXPHelper_ToggleXPNPCLocatorKeyCode = 0;
const int Ninja_MaxXPHelper_ToggleTrackersMaxRenderingLevelKeyCode = 0;
const int Ninja_MaxXPHelper_TrackersUseZBuffer = 0;
const int Ninja_MaxXPHelper_ToggleTrackersUseZBufferKeyCode = 0;
const int Ninja_MaxXPHelper_ConsiderG1DoubleXPGlitch = 0;
const int Ninja_MaxXPHelper_ConsiderLevelZeroNPC = 0;
const int Ninja_MaxXPHelper_ShowDeathAlerts = 0;
const string Ninja_MaxXPHelper_DeadOnArrivalNPCList = "";
const string Ninja_MaxXPHelper_DeathAlertsSVM = "";
const int Ninja_MaxXPHelper_TrackersRenderingLevel = 5;
const int Ninja_MaxXPHelper_ShowTrackerOnDeathAlert = 1;
const int Ninja_MaxXPHelper_DeathAlertTrackerDurationInMillis = 5000;
const int Ninja_MaxXPHelper_DeathAlertTextDurationInMillis = 5000;

const int Ninja_MaxXPHelper_DeathAlertsFailColor = 0;
const int Ninja_MaxXPHelper_SystemNotificationsColor = 0;